name: schedule-test

on:
  schedule:
    - cron: '15 14 * * 1-5'  # 台北 22:15
    - cron: '22 14 * * 1-5'  # 台北 22:22
    - cron: '31 14 * * 1-5'  # 台北 22:31
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello $(date)"
