name: schedule-test

on:
  schedule:
    - cron: '47 6 * * 1-5'  # 台北 14:47
    - cron: '2 7 * * 1-5'   # 台北 15:02
    - cron: '17 7 * * 1-5'  # 台北 15:17
    - cron: '32 7 * * 1-5'  # 台北 15:32
    - cron: '47 7 * * 1-5'  # 台北 15:47
    - cron: '2 8 * * 1-5'   # 台北 16:02
    - cron: '17 8 * * 1-5'  # 台北 16:17
    - cron: '32 8 * * 1-5'  # 台北 16:32
    - cron: '47 8 * * 1-5'  # 台北 16:47
    - cron: '2 9 * * 1-5'   # 台北 17:02
    - cron: '17 9 * * 1-5'  # 台北 17:17
    - cron: '32 9 * * 1-5'  # 台北 17:32
    - cron: '47 9 * * 1-5'  # 台北 17:47
    - cron: '2 10 * * 1-5'  # 台北 18:02
    - cron: '5 13 * * 1-5'  # 台北 21:05
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello $(date)"
