name: schedule-test

on:
  schedule:
    - cron: '50 13 * * 1-5'  # 台北 21:50
    - cron: '55 13 * * 1-5'  # 台北 21:55
    - cron: '0 14 * * 1-5'   # 台北 22:00
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello $(date)"
